apiVersion: 1

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    
    routes:
      # Production - Critique
      - receiver: grafana-default-email
        matchers:
          - environment = prod
          - severity = critical
        group_wait: 0s
        repeat_interval: 30m
      
      # Staging - Normal
      - receiver: grafana-default-email
        matchers:
          - environment = staging
        group_wait: 2m
        repeat_interval: 12h